baseURL = 'https://eliobou.github.io/'
languageCode = 'en-us'
title = 'eliobou'
theme = 'PaperMod'

# Pagination
pagination.pagerSize = 10

favicon = "/favicon.ico"

# Activation de la recherche
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  # Description du site
  description = "Mood and tech tutorials"
  author = "eliobou"
  
  apple_touch_icon = "/apple-touch-icon.png"

  # Mode sombre par d√©faut
  defaultTheme = "auto"  # auto, light, dark
  
  # Afficher le temps de lecture
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  
  # Page d'accueil
  [params.homeInfoParams]
    Title = "eliobou"
    Content = "mood & tech"

  # Liens sociaux
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/eliobou"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/eliott-bouchez"

  [[params.socialIcons]]
    name = "printables"
    url = "https://www.printables.com/@eliobou"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Menu
[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20
  
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 30

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Caches
[caches]
  [caches.images]
    dir = ':cacheDir/images'